services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - /:/shared
    ports:
      - 8006:8006
      - 5905:5905
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 10m
