name: /dev/sdc1 tester

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tester
        run: |
          sudo mkdir /sdc
          sudo mount /dev/sdc1 /sdc
          sudo ls /sdc
          lsblk
          df -h
