name: test

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tester
        run: |
          ls /dev
          mkdir sd
          mount sdb1 ./sd
          lscpu
          free -h
          df -h
          lsblk
